cobase_api_login:
    pattern: /oauth/v2/auth_login
    defaults: { _controller: CobaseApiBundle:Security:login }

cobase_api_login_check:
    pattern: /oauth/v2/auth_login_check
    defaults: { _controller: CobaseApiBundle:Security:loginCheck }

cobase_api_homepage:
    pattern:  /
    defaults: { _controller: CobaseApiBundle:Api:index }

cobase_api_post:
    type: rest
    resource: Cobase\ApiBundle\Controller\PostController
